app:
    version: '1조 - 0.0.2-SNAPSHOT'

spring:
    application:
        name: lotteon
        version: ${version}
    profiles:
        active: dev
        include: local
    thymeleaf:
        prefix: classpath:/templates/
