spring:
  datasource:
    url: jdbc:mysql://43.200.191.196:3306/lotteon
    username: root
    password: "qwer1234!Q"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      location: uploads/